server.port: 8080

customers:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

addresses:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081

spring:
  output:
    ansi:
      enabled: always
